apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-argocd-qa
  namespace: argocd
  labels:
    app: hello-world
    environment: qa
    essesseff: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/essesseff-hello-world-flask-template/hello-world-argocd-qa
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

