# ============================================================================
# Argo CD Repository Secrets for hello-world QA Environment
# ============================================================================
# 
# Apply this via ./setup-argocd.sh after installing Argo CD to your env-specific K8s cluster.
#
# IMPORTANT: Replace <your-argocd-machine-user> with your Argo CD machine username,
# and replace <your-github-token> with an actual GitHub personal 
# access token or deploy key *before* running ./setup-argocd.sh !  
#
# For detailed instructions on how to create a machine user and GitHub token,
# see: https://www.essesseff.com/docs/deployment/github-argocd-machine-user-setup 
#
# SECURITY: BE SURE TO DELETE OR EXCLUDE THIS FILE FROM GIT TO PREVENT
# COMMITTING YOUR GITHUB TOKEN(S) TO GITHUB!
#
# Required Permissions for GitHub Token:
#   - repo (Full control of private repositories)
#   - read:packages (Download packages from GitHub Container Registry)
# ============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-argocd-qa-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-flask-template/hello-world-argocd-qa
  password: <your-github-token>  # DO NOT COMMIT YOUR GITHUB TOKEN(S) TO GITHUB
  username: <your-argocd-machine-user>

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-config-qa-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/essesseff-hello-world-flask-template/hello-world-config-qa
  password: <your-github-token>  # DO NOT COMMIT YOUR GITHUB TOKEN(S) TO GITHUB
  username: <your-argocd-machine-user>

